name: Subito.it Screenshot

on:
  schedule:
    - cron: '0 */6 * * *' # Ogni 6 ore
  workflow_dispatch: # Permette avvio manuale

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Take Screenshot
        run: |
          node <<EOF
          const puppeteer = require('puppeteer');
          const fs = require('fs');

          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.setViewport({ width: 1200, height: 800 });
            await page.goto('https://impresapiu.subito.it/shops/54233-el-principe-di-bavaro-biagio', { waitUntil: 'networkidle2' });
            
            // Scroll to bottom per caricamento completo
            await page.evaluate(async () => {
              await new Promise((resolve) => {
                let totalHeight = 0;
                const distance = 100;
                const timer = setInterval(() => {
                  const scrollHeight = document.body.scrollHeight;
                  window.scrollBy(0, distance);
                  totalHeight += distance;
                  if(totalHeight >= scrollHeight){
                    clearInterval(timer);
                    resolve();
                  }
                }, 100);
              });
            });

            const screenshot = await page.screenshot({ fullPage: true });
            fs.writeFileSync('screenshot.png', screenshot);
            await browser.close();
          })();
          EOF

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add screenshot.png
          git commit -m "Update screenshot" || echo "No changes"
          git push
