name: Subito.it Screenshot Auto-Capture

on:
  schedule:
    - cron: '0 */6 * * *'  # Esegui ogni 6 ore
  workflow_dispatch:        # Permette avvio manuale
  push:
    branches: [ "main" ]    # Esegui su push (opzionale)

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install puppeteer

      - name: Take Screenshot
        run: |
          node <<EOF
          const puppeteer = require('puppeteer');
          const fs = require('fs');

          (async () => {
            const browser = await puppeteer.launch({ 
              headless: 'new',
              args: ['--no-sandbox', '--disable-setuid-sandbox']
            });
            
            const page = await browser.newPage();
            await page.setViewport({ width: 1200, height: 800 });
            
            console.log('Navigating to Subito.it...');
            await page.goto('https://impresapiu.subito.it/shops/54233-el-principe-di-bavaro-biagio', { 
              waitUntil: 'networkidle2',
              timeout: 60000 
            });

            // Scroll per caricare contenuti lazy-loaded
            console.log('Scrolling page...');
            await autoScroll(page);

            // Nascondi elementi indesiderati (personalizza)
            await page.evaluate(() => {
              const elements = document.querySelectorAll('.cookie-banner, .ads');
              elements.forEach(el => el.style.display = 'none');
            });

            console.log('Capturing screenshot...');
            const screenshot = await page.screenshot({ 
              fullPage: true,
              optimizeForSpeed: true
            });

            fs.writeFileSync('screenshot.png', screenshot);
            await browser.close();
            console.log('Done!');

            async function autoScroll(page) {
              await page.evaluate(async () => {
                await new Promise((resolve) => {
                  let totalHeight = 0;
                  const distance = 300;
                  const timer = setInterval(() => {
                    const scrollHeight = document.body.scrollHeight;
                    window.scrollBy(0, distance);
                    totalHeight += distance;
                    if(totalHeight >= scrollHeight) {
                      clearInterval(timer);
                      resolve();
                    }
                  }, 200);
                });
              });
            }
          })();
          EOF
          
      - name: Compress Image
        run: |
          sudo apt-get install -y optipng
          optipng -o7 screenshot.png
          

      - name: Upload Screenshot
        uses: actions/upload-artifact@v3
        with:
          name: subito-screenshot
          path: screenshot.png

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add screenshot.png
          git commit -m "Update screenshot [skip ci]" || echo "No changes"
          git push
